[package]
name = "rosc"
version = "0.1.0"
authors = ["Andreas Linz <klingt.net@gmail.com>"]
description = "An OSC library for Rust"
keywords = ["audio", "osc"]
documentation = "https://docs.klingt.net/rustdoc/rosc"
# homepage = "https://klingt.net"
repository = "https://git.klingt.net/alinz/rosc"
license = "GPLv3"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
byteorder = "0.3.13"
