[package]
name = "rosc"
version = "0.5.2"
authors = ["Andreas Linz <klingt.net@gmail.com>"]
description = "An OSC library for Rust"
keywords = ["audio", "osc"]
documentation = "https://docs.rs/rosc"
repository = "https://github.com/klingtnet/rosc"
license = "MIT/Apache-2.0"
readme = "README.md"

[features]
lints = ["clippy"]

[dependencies]
byteorder = "1"
clippy = {version="^0", optional=true}
